package com.bankstatement.common.enums;

public enum SagaStatus {
    STARTED,
    ACCOUNT_VALIDATED,
    ACCOUNT_VALIDATION_FAILED,
    CURRENCY_CONVERTED,
    CURRENCY_CONVERSION_FAILED,
    LEDGER_RECORDED,
    LEDGER_RECORDING_FAILED,
    STATEMENT_UPDATED,
    STATEMENT_UPDATE_FAILED,
    COMPLETED,
    COMPENSATING,
    COMPENSATION_COMPLETED,
    FAILED
}
